FROM node:lts-alpine3.18

ENV NODE_ENV=production

WORKDIR /app

ADD package.json package-lock.json ./

RUN npm install --production

ADD src ./src
ADD .env ./

CMD ["npm", "run", "serve"] // default command
